# Generated by Django 5.0.7 on 2024-08-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_category_name_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
