# Generated by Django 5.0.7 on 2024-09-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Версия товара', 'verbose_name_plural': 'Версии товаров'},
        ),
    ]
